# Pavel Soshenko Gnezdilov, 41071 - Operating Systems Project 1
# CSC1021/simpleshell

bin/simpleshell: src/simpleshell.c src/utility.c src/simpleshell.h
	gcc -Wall src/simpleshell.c src/utility.c -o ./bin/simpleshell